openapi: 3.0.3
info:
  title: Improview Backend API
  version: 0.1.0
  description: >-
    API contract derived from `internal/api.Server`. Endpoints are served under
    the `/api` prefix.
servers:
  - url: https://bh853brv47.execute-api.us-east-1.amazonaws.com
    description: Deployed dev environment ($default stage)
  - url: http://localhost:8080
    description: Local development server proxying the Go HTTP API
paths:
  /api/generate:
    post:
      summary: Generate a new problem pack
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateRequest'
      responses:
        '200':
          description: Problem pack created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenerateResponse'
        default:
          $ref: '#/components/responses/ErrorResponse'
  /api/attempt:
    post:
      summary: Create an attempt for a problem
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAttemptRequest'
      responses:
        '200':
          description: Attempt created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateAttemptResponse'
        default:
          $ref: '#/components/responses/ErrorResponse'
  /api/run-tests:
    post:
      summary: Execute tests for a specific attempt
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RunTestsRequest'
      responses:
        '200':
          description: Test summary
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RunTestsResponse'
        default:
          $ref: '#/components/responses/ErrorResponse'
  /api/submit:
    post:
      summary: Finalize an attempt and run hidden tests
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubmitRequest'
      responses:
        '200':
          description: Submission summary
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubmitResponse'
        default:
          $ref: '#/components/responses/ErrorResponse'
  /api/attempt/{attempt_id}:
    get:
      summary: Retrieve attempt metadata and runs
      parameters:
        - name: attempt_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Attempt with recorded runs
          content:
            application/json:
              schema:
                type: object
                properties:
                  attempt:
                    $ref: '#/components/schemas/Attempt'
                  runs:
                    type: array
                    items:
                      $ref: '#/components/schemas/RunResult'
                required:
                  - attempt
                  - runs
        default:
          $ref: '#/components/responses/ErrorResponse'
  /api/problem/{problem_id}:
    get:
      summary: Fetch a generated problem pack
      parameters:
        - name: problem_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Problem pack payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemPack'
        default:
          $ref: '#/components/responses/ErrorResponse'
  /api/healthz:
    get:
      summary: Check backend health
      responses:
        '200':
          description: Service healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                required:
                  - status
        default:
          $ref: '#/components/responses/ErrorResponse'
  /api/version:
    get:
      summary: Retrieve backend version
      responses:
        '200':
          description: Version string
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string
                    example: v0.1.0
                required:
                  - version
        default:
          $ref: '#/components/responses/ErrorResponse'
components:
  schemas:
    GenerateRequest:
      type: object
      properties:
        category:
          type: string
        difficulty:
          type: string
        customPrompt:
          type: string
        provider:
          type: string
      required:
        - category
        - difficulty
    GenerateResponse:
      type: object
      properties:
        problem_id:
          type: string
        pack:
          $ref: '#/components/schemas/ProblemPack'
      required:
        - problem_id
        - pack
    CreateAttemptRequest:
      type: object
      properties:
        problem_id:
          type: string
        lang:
          type: string
        user_id:
          type: string
      required:
        - problem_id
        - lang
    CreateAttemptResponse:
      type: object
      properties:
        attempt:
          $ref: '#/components/schemas/Attempt'
      required:
        - attempt
    RunTestsRequest:
      type: object
      properties:
        attempt_id:
          type: string
        code:
          type: string
        which:
          type: string
      required:
        - attempt_id
        - code
        - which
    RunTestsResponse:
      type: object
      properties:
        summary:
          $ref: '#/components/schemas/RunSummary'
      required:
        - summary
    SubmitRequest:
      type: object
      properties:
        attempt_id:
          type: string
        code:
          type: string
      required:
        - attempt_id
        - code
    SubmitResponse:
      type: object
      properties:
        summary:
          $ref: '#/components/schemas/SubmissionSummary'
      required:
        - summary
    ProblemPack:
      type: object
      properties:
        problem:
          $ref: '#/components/schemas/ProblemMetadata'
        api:
          $ref: '#/components/schemas/APISignature'
        time_estimate_minutes:
          type: integer
          format: int32
        hint:
          type: string
        solutions:
          type: array
          items:
            $ref: '#/components/schemas/SolutionOutline'
        tests:
          $ref: '#/components/schemas/TestSuite'
      required:
        - problem
        - api
        - time_estimate_minutes
        - hint
        - solutions
        - tests
    ProblemMetadata:
      type: object
      properties:
        title:
          type: string
        statement:
          type: string
        constraints:
          type: array
          items:
            type: string
        examples:
          type: array
          items:
            $ref: '#/components/schemas/Example'
        edge_cases:
          type: array
          items:
            type: string
      required:
        - title
        - statement
        - constraints
        - examples
        - edge_cases
    Example:
      type: object
      properties:
        input:
          type: array
          items: {}
        output:
          nullable: true
        explanation:
          type: string
      required:
        - input
        - output
    APISignature:
      type: object
      properties:
        function_name:
          type: string
        signature:
          type: string
        params:
          type: array
          items:
            $ref: '#/components/schemas/APIParam'
        returns:
          $ref: '#/components/schemas/APIParamReturn'
      required:
        - function_name
        - signature
        - params
        - returns
    APIParam:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
        desc:
          type: string
      required:
        - name
        - type
        - desc
    APIParamReturn:
      type: object
      properties:
        type:
          type: string
        desc:
          type: string
      required:
        - type
        - desc
    SolutionOutline:
      type: object
      properties:
        approach:
          type: string
        complexity:
          $ref: '#/components/schemas/Complexity'
        code:
          type: string
      required:
        - approach
        - complexity
        - code
    Complexity:
      type: object
      properties:
        time:
          type: string
        space:
          type: string
      required:
        - time
        - space
    TestSuite:
      type: object
      properties:
        public:
          type: array
          items:
            $ref: '#/components/schemas/Example'
        hidden:
          type: array
          items:
            $ref: '#/components/schemas/Example'
      required:
        - public
        - hidden
    Attempt:
      type: object
      properties:
        id:
          type: string
        problem_id:
          type: string
        user_id:
          type: string
        lang:
          type: string
        started_at:
          type: integer
          format: int64
        ended_at:
          type: integer
          format: int64
        hint_used:
          type: boolean
        pass_count:
          type: integer
          format: int32
        fail_count:
          type: integer
          format: int32
        duration_ms:
          type: integer
          format: int64
      required:
        - id
        - problem_id
        - user_id
        - lang
        - started_at
        - ended_at
        - hint_used
        - pass_count
        - fail_count
        - duration_ms
    RunResult:
      type: object
      properties:
        test_id:
          type: string
        status:
          type: string
        time_ms:
          type: integer
          format: int64
        stdout:
          type: string
        stderr:
          type: string
      required:
        - test_id
        - status
        - time_ms
        - stdout
        - stderr
    RunSummary:
      type: object
      properties:
        attempt_id:
          type: string
        results:
          type: array
          items:
            $ref: '#/components/schemas/RunResult'
      required:
        - attempt_id
        - results
    SubmissionSummary:
      type: object
      properties:
        attempt_id:
          type: string
        passed:
          type: boolean
        runtime_ms:
          type: integer
          format: int64
        operations:
          type: integer
          format: int64
        hidden_results:
          type: array
          items:
            $ref: '#/components/schemas/RunResult'
      required:
        - attempt_id
        - passed
        - runtime_ms
        - operations
        - hidden_results
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
      required:
        - error
  responses:
    ErrorResponse:
      description: Error response envelope
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
